POST http://localhost:3000/auth
content-type: application/json

{
    "login": "login1",
    "password": "password1"
}
###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImxvZ2luMSIsImlkIjoiYjc3Y2U2MGQtYTU5Ny00NjUxLTg5M2QtNjc5MmExNjZjZDJhIiwiaWF0IjoxNjA5MjY5MTY0LCJleHAiOjE2MDkyNjk0NjR9.O6IQv6Epa2-i-WBYB3EDXWrUa4o0YiYPqZClU6ODreo
